<?php require '../model/save_student.php'; ?>
<form action="" method="POST">
	<div class="text-center">Password: First Name and Username </div>
	<input type="hidden" name="student_id" value="<?php if(isset($_GET['studentId'])) echo $fetchedStudent['student_id']; ?>"/>
	<input type="hidden" name="role" value="student"/>
	<input type="hidden" name="status" value="0"/>
	<h1>Add New Users</h1>
	<div class="form-group">
		<label>Student's UID:</label>
		<input class="form-control" type="text" name="user_id" value="<?php if(isset($_GET['studentId'])){ echo $fetchedStudent['user_id'];} else{ echo 'User id is autogenerated'; }?>" readonly/>
	</div> 
	<div class="form-group">
		<label>First Name:<span class="text-danger">****</span></label>
		<input class="form-control" type="text" name="first_name" value="<?php if(isset($_GET['studentId'])) echo $fetchedStudent['first_name']; ?>">
	</div>
	<div class="form-group">
		<label>Middle Name:</label>
		<input class="form-control" type="text" name="middle_name" placeholder="optional" value="<?php if(isset($_GET['studentId'])) echo $fetchedStudent['middle_name']; ?>">
	</div>
	<div class="form-group">
		<label>Last Name:<span class="text-danger">****</span></label>
		<input class="form-control" type="text" name="surname" value="<?php if(isset($_GET['studentId'])) echo $fetchedStudent['surname']; ?>">
	</div>
	<div class="form-group">
		<label>Username:<span class="text-danger">****</span></label>
		<input class="form-control" type="text" name="username" value="<?php if(isset($_GET['studentId'])) echo $fetchedStudent['username']; ?>">
	</div>
	<div class="form-group">
		<label>Email:<span class="text-danger">****</span></label>
		<input class="form-control" type="email" name="email" value="<?php if(isset($_GET['studentId'])) echo $fetchedStudent['email']; ?>">
	</div>
	<div class="form-group">
		<label>Date of Birth:</label>
		<input class="form-control" type="date" name="date_of_birth" value="<?php if(isset($_GET['studentId'])) echo $fetchedStudent['date_of_birth']; ?>">
	</div>
	<div class="form-group">
		<label>Gender:</label>
		<select class="form-control" name="gender">
			<option value="M">Male</option>
			<option value="F">Female</option>
		</select>
	</div>
	<div class="form-group">
		<label>Phone Number:</label>
		<input class="form-control" type="text" name="phone_number" value="<?php if(isset($_GET['studentId'])) echo $fetchedStudent['phone_number']; ?>">
	</div>
	<div class="form-group">
		<label>Father's Name:</label>
		<input class="form-control" type="text" name="father_name" value="<?php if(isset($_GET['studentId'])) echo $fetchedStudent['father_name']; ?>">
	</div>
	<div class="form-group">
		<label>Mother's Name:</label>
		<input class="form-control" type="text" name="mother_name" value="<?php if(isset($_GET['studentId'])) echo $fetchedStudent['mother_name']; ?>">
	</div>
	<div class="form-group">
		<label>Parent's Contact:</label>
		<input class="form-control" type="text" name="parent_contact" value="<?php if(isset($_GET['studentId'])) echo $fetchedStudent['parent_contact']; ?>">
	</div>
	<div class="form-group">
		<label>Father's Email: </label>
		<input class="form-control" type="email" name="father_email" value="<?php if(isset($_GET['studentId'])) echo $fetchedStudent['father_email']; ?>">
	</div>
	<div class="form-group">
		<label>Course Assigned </label>
		<select class="form-control" name="course_assign">
			<?php foreach ($courseName as $courseAsRow) { ?>
				<option value="<?php echo $courseAsRow['course_id']; ?>"><?php echo $courseAsRow['course_name'] ?></option>
			<?php } ?>
		</select>
	</div>
	
	<div class="form-group">
		<label>Year:</label>
		<div class="radio" name="year">
			<label class="radio-inline"><input type="radio" name="year" value="1" checked/>Year 1</label>
			<label class="radio-inline"><input type="radio" name="year" value="2" />Year 2</label>
			<label class="radio-inline"><input type="radio" name="year" value="3" />Year 3</label>
		</div>
	</div>
	<div class="form-group">
		<label>Passed Out </label>
		<select class="form-control" name="passed_out">
			<option value="0">No</option>
			<option value="1">Yes</option>
		</select>
	</div>
	<input class="btn btn-primary" type="submit" name="submit" value="Submit"/>	
</form>